# Site settings
title: SocSciStats
email: ekt.batey@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Exploring social science statistical analysis and data visualization with R and other open-source tools.
baseurl: "/socscistats" # the subpath of your site, e.g. /blog/
url: "http://tbatey.org" # the base hostname & protocol for your site
twitter_username: bateytk
github_username:  bateyt
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
