---
layout: post
title: "Quick maps with R"
author: "Trey Batey"
date: "December 8, 2016"
categories: [spatial, rstats]
tags: [ggmaps, ggplot2]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.align = "center")
knitr::opts_chunk$set(fig.height = 7)
knitr::opts_chunk$set(fig.width = 12)
```

Social scientists commonly need to visualize data across geographic space. Fortunately, R has many packages and functions for quickly producing vector and raster-based maps. For example, with just two short lines of code, we can produce a map of the United States.

```{r echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
packs <- c('ggplot2', 'ggmap', 'ggvis', 'scales', 'dplyr', 'googlesheets', 'rgdal', 'spatial', 'maps', 'maptools', 'mapdata', 'raster', 'sp', 'mapproj')
lapply(packs, require, character.only = TRUE)
```

```{r}
us <- get_map('usa', zoom = 3)
ggmap(us)
```
Or, we can use the `maps` package and display a vector map of the U. S.

```{r}
us2 <- map("usa")
us2.df <- fortify(us2)
ggplot(data = us2.df, aes(x = long, y = lat)) + geom_polygon() 
```
